### ISSUE TITLE
How to pass extra parameter in the order api 

### ISSUE THREAD

**Issue by rashmisridar** [kushalmahapatro/flutter_instamojo#2]
In this api "https://instamojo-dart-server.herokuapp.com/order".  Have the parameters like "createOrderBody" in that amount, buyer_email,buyer_name,buyer_phone,description . How to add the extra parameter ?

**Comment by kushalmahapatro** [comment]
@rashmisridar
 
These all the main parameters required to create order. Actually "https://instamojo-dart-server.herokuapp.com/order" is my personal API created in dart for order creation. 

So all the test and live payment request will be coming to my dashboArd. Please use instamojo's sample sdk server "https://sample-sdk-server.instamojo.com/order" for order creation and want to set ur own server with your instamojo's key, please have a look at my my dart server "https://github.com/kushalmahapatro/instamojo_dart_apis" or instamojo's go server "https://github.com/Instamojo/sample-sdk-server"
